//>>built
define("dgrid/editor","dojo/_base/kernel,dojo/_base/lang,dojo/_base/array,dojo/_base/Deferred,dojo/on,dojo/aspect,dojo/has,./Grid,put-selector/put,dojo/_base/sniff".split(","),function(y,q,z,r,i,m,n,s,o){function t(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=!!b}function u(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date)var c=new Date(a),a=isNaN(c.getTime())?a:c;return a}function A(a,b,c,
d){var f,e,g;if(!(c>=d&&c<=d)&&(f=a.cell(b),e=f.row,g=f.column,g.field&&e))if(i.emit(b,"dgrid-datachange",{grid:this,cell:f,rowId:e.id,oldValue:c,value:d,bubbles:!0,cancelable:!0}))a.updateDirty&&(a.updateDirty(e.id,g.field,d),g.autoSave&&setTimeout(function(){a._trackError("save")},0));else return c;return d}function p(a,b,c){if(!c.isValid||c.isValid())a=A(a,(c.domNode||c).parentNode,h?j:c._dgridLastValue,"function"==typeof c.get?u(c.get("value")):u(c["checkbox"==c.type||"radio"==c.type?"checked":
"value"])),h?j=a:c._dgridLastValue=a}function v(a){var b=a.editor,c=a.editOn,d=a.grid,f="string"!=typeof b,e,g,k;e=a.editorArgs||{};"function"==typeof e&&(e=e.call(d,a));if(f)g=new b(e),f=g.focusNode||g.domNode,f.className+=" dgrid-input",g.connect(g,c?"onBlur":"onChange",function(){g._dgridIgnoreChange||p(d,a,this)});else{k=function(b){b=b.target;"_dgridLastValue"in b&&-1<b.className.indexOf("dgrid-input")&&p(d,a,b)};if(!a.grid._hasInputListener)d._hasInputListener=!0,d.on("change",function(a){k(a)});
g=f=o(("textarea"==b?"textarea":"input[type="+b+"]")+".dgrid-input",q.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},e));if(9>n("ie")||n("ie")&&n("quirks"))"radio"==b||"checkbox"==b?i(g,"click",function(a){k(a)}):i(g,"change",function(a){k(a)})}i(f,"mousedown",function(a){a.stopPropagation()});return g}function B(a){var b=v(a),c=b.domNode||b,d=b.focusNode||c,f=b.domNode?function(){b.set("value",b._dgridLastValue)}:function(){t(b,b._dgridLastValue);p(a.grid,a,b)};i(d,"keydown",function(c){c=
c.keyCode||c.which;27==c?(f(),j=b._dgridLastValue,d.blur()):13==c&&!1!==a.dismissOnEnter&&d.blur()});(a._editorBlurHandle=i.pausable(b,"blur",function(){var b=c.parentNode;a.grid.cell(c);var g=b.children.length-1,d={alreadyHooked:!0};for(b.removeChild(c);g--;)o(b.firstChild,"!");s.appendIfNode(b,a.renderCell(a.grid.row(b).data,j,b,l?q.delegate(d,l):d));h=j=l=null;a._editorBlurHandle.pause()})).pause();return b}function w(a,b,c,d){(b=a.domNode)||t(a,d);c.innerHTML="";o(c,a.domNode||a);if(b)a._started||
a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0);a._dgridLastValue=d;h&&(j=d)}function x(a){var b,c,d,f,e,g;a.column||(a=this.cell(a));b=a.column;f=b.field;c=a.element.contents||a.element;if(e=b.editorInstance){if(h!=c&&(!b.canEdit||b.canEdit(a.row.data,d)))return h=c,a=a.row,d=(d=this.dirty&&this.dirty[a.id])&&f in d?d[f]:b.get?b.get(a.data):a.data[f],w(b.editorInstance,b,c,d),g=new r,setTimeout(function(){e.focus&&e.focus();b._editorBlurHandle&&
b._editorBlurHandle.resume();g.resolve(e)},0),g.promise}else if(b.editor&&(e=c.widget||c.input))return g=new r,e.focus&&e.focus(),g.resolve(e),g.promise;return null}var h,j,l;return function(a,b,c){var d=a.renderCell||s.defaultRenderCell,f=[],e;a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;e="string"!=typeof b;if(a.widgetArgs)y.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs;m.after(a,"init",c?function(){var b=a.grid;if(!b.edit)b.edit=
x;a.editorInstance=B(a,d)}:function(){var b=a.grid;if(!b.edit)b.edit=x;e&&f.push(m.before(b,"removeRow",function(c){c=b.cell(c,a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});m.after(a,"destroy",function(){z.forEach(f,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();c&&e&&a.editorInstance.destroyRecursive()});a.renderCell=c?function(b,e,f,h){if(!h||!h.alreadyHooked)i("TD"==f.tagName?f:f.parentNode,c,function(){l=h;a.grid.edit(this)});return d.call(a,b,
e,f,h)}:function(b,c,d){b=v(a);w(b,a,d,c);d[e?"widget":"input"]=b};return a}});