//>>built
define("dgrid/Grid","dojo/_base/kernel,dojo/_base/declare,dojo/on,dojo/has,put-selector/put,./List,dojo/_base/sniff".split(","),function(r,g,t,h,i,u){function m(a,b){b&&b.nodeType&&a.appendChild(b)}var s=8>h("ie")&&!h("quirks"),v=/[^\._a-zA-Z0-9-]/g,g=g([u],{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,column:function(a){return"string"==typeof a?this.columns[a]:this.cell(a).column},listType:"grid",cell:function(a,b){if(a.row&&a.row instanceof this._Row)return a;if(a.target&&a.target.nodeType)a=
a.target;var c;if(a.nodeType){do{if(this._rowIdToObject[a.id])break;var f=a.columnId;if(f){b=f;c=a;break}a=a.parentNode}while(a&&a!=this.domNode)}if(!c&&b){var e=this.row(a);if(f=e.element)for(var f=f.getElementsByTagName("td"),d=0;d<f.length;d++)if(f[d].columnId==b){c=f[d];break}}if(null!=a)return{row:e||this.row(a),column:b&&this.column(b),element:c}},_columnsCss:function(a){a.fullSelector=function(){return this.parent.fullSelector()+" .dgrid-cell"};for(var b=0;b<a.children.length;b++){var c=a.children[b];
c.field=c.className=c.selector.substring(1)}return a.children},createRowCells:function(a,b,c){var f=i("table.dgrid-row-table[role=presentation]"),e=9>h("ie")||h("quirks")?i(f,"tbody"):f,d,n,p,g,m,q,k,l,j,o,c=c||this.subRows;for(n=0,p=c.length;n<p;n++){q=c[n];d=1==p&&!h("ie")?e:i(e,"tr");for(g=0,m=q.length;g<m;g++){k=q[g];l=k.id;j=k.className||k.field&&"field-"+k.field;j=i(a+(".dgrid-cell.dgrid-cell-padding.dgrid-column-"+l+(j?"."+j:"")).replace(v,"-"));j.columnId=l;s?(l=i(j,"!dgrid-cell-padding div.dgrid-cell-padding"),
j.contents=l):l=j;if(o=k.colSpan)j.colSpan=o;if(o=k.rowSpan)j.rowSpan=o;b(l,k);d.appendChild(j)}}return f},left:function(a,b){return this.cell(this._move(a,-(b||1),"dgrid-cell"))},right:function(a,b){return this.cell(this._move(a,b||1,"dgrid-cell"))},renderRow:function(a,b){var c=this.createRowCells("td",function(f,e){var d=a;e.get?d=e.get(a):"field"in e&&"_item"!=e.field&&(d=d[e.field]);e.formatter?f.innerHTML=e.formatter(d):e.renderCell?m(f,e.renderCell(a,d,f,b)):null!=d&&f.appendChild(document.createTextNode(d))},
b&&b.subRows);return i("div[role=gridcell]>",c)},renderHeader:function(){for(var a=this,b=this.headerNode,c=b.childNodes.length;c--;)i(b.childNodes[c],"!");c=this.createRowCells("th[role=columnheader]",function(a,b){var d=b.headerNode=a;if(s)a=a.parentNode;var c=b.field;if(c)a.field=c;if(b.renderHeaderCell)m(d,b.renderHeaderCell(d));else if(b.label||b.field)d.appendChild(document.createTextNode(b.label||b.field));if(!1!==b.sortable&&c&&"_item"!=c)a.sortable=!0,a.className+=" dgrid-sortable"});this._rowIdToObject[c.id=
this.id+"-header"]=this.columns;b.appendChild(c);t(c,"click,keydown",function(c){if("click"==c.type||32==c.keyCode){var c=c.target,e,d;do if(c.sortable)return a._sortNode=c,c=c.field||c.columnId,e=(d=a._sort[0])&&d.attribute==c&&!d.descending,a.set("sort",c,e);while((c=c.parentNode)&&c!=b)}})},resize:function(){var a=this.headerNode.firstChild,b=this.contentNode,c;this.inherited(arguments);if(!h("ie")||7<h("ie")&&!h("quirks"))if(b.style.width="",b&&a&&(c=a.offsetWidth)!=b.offsetWidth)b.style.width=
c+"px"},destroy:function(){this._destroyColumns();this.inherited(arguments)},_setSort:function(a,b){this.inherited(arguments);this._lastSortedArrow&&(i(this._lastSortedArrow,"<!dgrid-sort-up!dgrid-sort-down"),i(this._lastSortedArrow,"!"),delete this._lastSortedArrow);if(this._sort[0]){var c=this._sort[0].attribute,f=this._sort[0].descending,e=this._sortNode,d,g,h;delete this._sortNode;if(!e)for(h in d=this.columns,d)if(g=d[h],g.field==c){e=g.headerNode;break}if(e)e=e.contents||e,this._lastSortedArrow=
i(e.firstChild,"-div.dgrid-sort-arrow.ui-icon[role=presentation]"),this._lastSortedArrow.innerHTML="&nbsp;",i(e,f?".dgrid-sort-down":".dgrid-sort-up"),this.resize()}},styleColumn:function(a,b){return this.addCssRule("#"+this.domNode.id+" .dgrid-column-"+a,b)},_configColumns:function(a,b){var c=[],f=b instanceof Array,e,d;for(e in b){d=b[e];"string"==typeof d&&(b[e]=d={label:d});if(!f&&!d.field)d.field=e;e=d.id=d.id||(isNaN(e)?e:a+e);a&&(this.columns[e]=d);this._configColumn&&this._configColumn(d,
e,b,a);d.grid=this;"function"===typeof d.init&&d.init();c.push(d)}return f?b:c},_destroyColumns:function(){var a=this.subRows.length,b,c,f;this.cleanup();for(b=0;b<a;b++)for(c=0,len=this.subRows[b].length;c<len;c++)f=this.subRows[b][c],"function"===typeof f.destroy&&f.destroy()},configStructure:function(){var a=this.subRows;if(a){this.columns={};for(var b=0;b<a.length;b++)a[b]=this._configColumns(b+"-",a[b])}else this.subRows=[this._configColumns("",this.columns)]},_setColumns:function(a){this._destroyColumns();
this.subRows=null;this.columns=a;this._updateColumns()},_setSubRows:function(a){this._destroyColumns();this.subRows=a;this._updateColumns()},setColumns:function(a){r.deprecated("setColumns(...)",'use set("columns", ...) instead',"dgrid 1.0");this.set("columns",a)},setSubRows:function(a){r.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",a)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);
this.resize()}});g.appendIfNode=m;g.defaultRenderCell=function(a,b,c){null!=b&&c.appendChild(document.createTextNode(b))};return g});