//>>built
define("dgrid/List","dojo/_base/array,dojo/_base/kernel,dojo/_base/declare,dojo/on,dojo/has,./util/misc,dojo/has!touch?./TouchScroll,xstyle/has-class,put-selector/put,dojo/_base/sniff,xstyle/css!./css/dgrid.css".split(","),function(w,p,q,m,i,s,r,t,e){function n(a,b,c,f){var d,h;h=d=a.element;b=b||1;do if(a=d[0>b?"previousSibling":"nextSibling"]){do if(d=a,-1<((d&&d.className)+" ").indexOf(c+" ")){h=d;b+=0>b?1:-1;break}while(a=(!f||!d.hidden)&&d[0>b?"lastChild":"firstChild"])}else if((d=d.parentNode)==
this.domNode||-1<(d.className+" ").indexOf("dgrid-row "))break;while(b);return h}t("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var k,g=e(document.getElementsByTagName("head")[0],"style"),l=[],g=g.sheet||g.styleSheet,u=0,v=7>i("ie")&&!i("quirks")?function(a){var b,c,f;if(a._started&&(b=document.documentElement,c=b.clientWidth,b=b.clientHeight,f=a._prevWinDims||[],f[0]!==c||f[1]!==b))a.resize(),a._prevWinDims=[c,b]}:function(a){a._started&&a.resize()};return q(r?[r]:
[],{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=function(){c.removeRow(this.element)};if(b)this.srcNodeRef=b=b.nodeType?b:document.getElementById(b);this.create(a,b)},listType:"list",create:function(a,b){a?(this.params=a,q.safeMixin(this,a),this._sort=a.sort||[],delete this.sort):this._sort=[];var c=this.domNode=b||e("div");this.observers=[];this._listeners=[];
this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+u++;this.buildRendering();this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b,c,f,d;d=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();e(a,"[role=grid].ui-widget.dgrid.dgrid-"+this.listType);b=this.headerNode=e(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+
(this.showHeader?"":".dgrid-header-hidden"));(i("quirks")||8>i("ie"))&&e(a,"div.dgrid-spacer");c=this.bodyNode=this.touchNode=e(a,"div.dgrid-scroller");c.tabIndex=-1;this.headerScrollNode=e(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");f=this.footerNode=e("div.dgrid-footer");if(!this.showFooter)f.style.display="none";e(a,f);d&&(a.className+=" dgrid-rtl"+(i("webkit")?"":" dgrid-rtl-nonwebkit"));m(c,"scroll",function(d){b.scrollLeft=c.scrollLeft;d.stopPropagation();m.emit(a,"scroll",
{scrollTarget:c})});this.configStructure();this.renderHeader();this.contentNode=e(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=m(window,"resize",s.debounce(v)))},startup:function(){this.inherited(arguments);if(!this._started)this._started=!0,this.resize(),this.set("sort",this._sort)},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,f=b.offsetHeight,d=this.showFooter?c.offsetHeight:0,h=i("quirks")||
7>i("ie");this.headerScrollNode.style.height=a.style.marginTop=f+"px";if(d)a.style.marginBottom=d+"px";if(h&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-f-d,0)+"px",d))c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0);k||(f=e(document.body,"div.dgrid-scrollbar-measure"),k=f.offsetWidth-f.clientWidth,e(f,"!"),7===i("ie")&&k++,this.addCssRule(".dgrid-scrollbar-width","width: "+k+"px"),this.addCssRule(".dgrid-scrollbar-height","height: "+k+"px"),17!=k&&!h&&(this.addCssRule(".dgrid-header",
"right: "+k+"px"),this.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header","left: "+k+"px")));if(h)b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0)},addCssRule:function(a,b){var c=l.length;l[c]=(g.cssRules||g.rules).length;g.addRule?g.addRule(a,b):g.insertRule(a+"{"+b+"}",l[c]);return{remove:function(){var a=l[c],b,h=l.length;if(void 0!==a){g.deleteRule?g.deleteRule(a):g.removeRule(a);l[c]=void 0;for(b=c;b<h;b++)l[b]>a&&l[b]--}}}},on:function(a,b){var c=m(this.domNode,
a,b);i("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners;this.cleanup();e("!",this.domNode)},refresh:function(){this.cleanup();this._rowIdToObject=
{};this._autoId=0;this.contentNode.innerHTML=""},newRow:function(a,b,c,f){if(b.parentNode){var d=this.insertRow(a,b.parentNode,b,f.start+c,f);e(d,".ui-state-highlight");setTimeout(function(){e(d,"!ui-state-highlight")},250);return d}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;do if(-1<a.rowIndex)e(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++;while((a=a.nextSibling)&&a.rowIndex!=b)}},renderArray:function(a,
b,c){function f(a){o=h.insertRow(a,l,null,e++,c);o.observerIndex=k;return o}function d(a){if(i=b?b.parentNode:h.contentNode)i.insertBefore(l,b||null),(o=a[a.length-1])&&h.adjustRowIndices(o);return j=a}var c=c||{},h=this,e=c.start||0,g,j,i;if(!b)this._lastCollection=a;if(a.observe)var k=this.observers.push(a.observe(function(a,d,f){var e;if(-1<d&&j[d]){g=j.splice(d,1)[0];if(g.parentNode==i&&(e=g.nextSibling))e.rowIndex--,h.removeRow(g);h._processScroll&&h._processScroll()}if(-1<f){if(g=h.newRow(a,
j[f]||j[f-1]&&j[f-1].nextSibling||b,f,c))if(g.observerIndex=k,j.splice(f,0,g),!e||f<e.rowIndex)e=g;c.count++}d!=f&&e&&h.adjustRowIndices(e)},!0))-1;var l=document.createDocumentFragment();if(a.map){if(j=a.map(f,console.error),j.then)return j.then(d)}else{j=[];for(var m=0,n=a.length;m<n;m++)j[m]=f(a[m])}var o;return d(j)},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,f,d){var e=this.id+"-row-"+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),g=document.getElementById(e);
if(!g||c&&g.parentNode!=c.parentNode)g&&this.removeRow(g),g=this.renderRow(a,d),g.className=(g.className||"")+" ui-state-default dgrid-row "+(1==f%2?"dgrid-row-odd":"dgrid-row-even"),this._rowIdToObject[g.id=e]=a;b.insertBefore(g,c);g.rowIndex=f;return g},renderRow:function(a){return e("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||e(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;if(a.target&&a.target.nodeType)a=a.target;if(a.nodeType){do{var c=
a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},_move:n,up:function(a,b,c){return this.row(n(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){return this.row(n(a,b||1,"dgrid-row",c))},get:function(a){var b="_get"+
a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();if(this._lastCollection){if(a.length){if("string"!=typeof a)b=
a[0].descending,a=a[0].attribute;this._lastCollection.sort(function(c,f){var d=c[a],e=f[a];void 0===d&&(d="");void 0===e&&(e="");return d==e?0:d>e==!b?1:-1})}this.renderArray(this._lastCollection)}},sort:function(a,b){p.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){this.showHeader=a;e(this.headerNode,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize()},setShowHeader:function(a){p.deprecated("setShowHeader(...)",
'use set("showHeader", ...) instead',"dgrid 1.0");this.set("showHeader",a)}})});