//>>built
define("dgrid/OnDemandList","./List,./_StoreMixin,dojo/_base/declare,dojo/_base/lang,dojo/_base/Deferred,dojo/on,./util/misc,put-selector/put".split(","),function(y,z,A,B,p,C,q,l){return A([y,z],{minRowsPerPage:25,maxRowsPerPage:100,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:1E4,rowHeight:22,queryRowsOverlap:1,pagingDelay:q.defaultDelay,postCreate:function(){this.inherited(arguments);var d=this;C(this.bodyNode,"scroll",q.throttleDelayed(function(i){d._processScroll(i)},null,this.pagingDelay))},
renderQuery:function(d,i){var b={query:d,count:0,node:i};if(!i){var e={node:l(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:d,next:b};b.node=i=l(this.contentNode,"div.dgrid-preload");b.previous=e}i.rowIndex=this.minRowsPerPage;(e=this.preload)?((b.next=e.next)&&this.bodyNode.scrollTop>=e.node.offsetTop?b.previous=e:(b.next=e,b.previous=e.previous),b.previous.next=b,b.next.previous=b):this.preload=b;var h=l(i,"-div.dgrid-loading");l(h,"div.dgrid-below",this.loadingMessage);var e=
B.mixin(this.get("queryOptions"),{start:0,count:this.minRowsPerPage,query:d}),j=d(e),k=this;p.when(this.renderArray(j,i,e),function(f){return p.when(j.total||j.length,function(a){l(h,"!");var d=f.length,a=a||d;if(!a)l(k.contentNode,"div.dgrid-no-data").innerHTML=k.noDataMessage;for(var e=0,j=0;j<d;j++)e+=f[j].offsetHeight;if(d&&e)k.rowHeight=e/d;a-=d;b.count=a;i.rowIndex=d;a?i.style.height=Math.min(a*k.rowHeight,k.maxEmptySpace)+"px":i.style.display="none";k._processScroll();return f})});return j},
refresh:function(){this.inherited(arguments);if(this.store){var d=this;this._trackError(function(){return d.renderQuery(function(i){return d.store.query(d.query,i)})})}},_calcRowHeight:function(d){return d.offsetHeight},lastScrollTop:0,_processScroll:function(){function d(a,c,d,f){var g=b.farOffRemoval,e=a.node;if(c>2*g){for(var h,j=e[d],k=0,m=0,n=[];h=j;){var o=b._calcRowHeight(h);if(k+o+g>c||0>j.className.indexOf("dgrid-row")&&0>j.className.indexOf("dgrid-loading"))break;var j=h[d],t,p=h.observerIndex;
if(p!=t&&-1<t){var q=b.observers,r=q[t];r&&r.cancel();q[t]=0}k+=o;m+=h.count||1;t=p;b.removeRow(h,!0);n.push(h)}a.count+=m;f?(e.rowIndex-=m,i(a)):e.style.height=e.offsetHeight+k+"px";for(var s=l("div"),a=0;a<n.length;a++)l(s,n[a]);setTimeout(function(){l(s,"!")},1)}}function i(a,c){a.node.style.height=Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+"px"}var b=this,e=b.bodyNode,h=b.contentNode.style.webkitTransform,h=e.scrollTop+(h?-h.match(/translate[\w]*\(.*?,(.*?)px/)[1]:0),j=e.offsetHeight+
h,k,f,a=b.preload,q=b.lastScrollTop,v=b.bufferRows*b.rowHeight,w=v-b.rowHeight;for(b.lastScrollTop=h;a&&a!=k;){k=b.preload;b.preload=a;f=a.node;var c=f.offsetTop;if(j+1+w<c){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(h-1-w>c+f.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var g=((f.rowIndex?h-v:j)-c)/b.rowHeight,c=(j-h+2*v)/b.rowHeight,r=Math.max(Math.min((h-q)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),c=c+Math.min(Math.abs(r),10);0==f.rowIndex&&(g-=c);g=Math.max(g,
0);10>g&&0<g&&c+g<b.maxRowsPerPage&&(c+=Math.max(0,g),g=0);c=Math.min(Math.max(c,b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==c)break;var c=Math.ceil(c),g=Math.min(Math.floor(g),a.count-c),n=b.get("queryOptions");a.count-=c;var m=f,s,u=b.queryRowsOverlap;if(r=0<f.rowIndex&&a){var o=a.previous;o&&(d(o,h-(o.node.offsetTop+o.node.offsetHeight),"nextSibling"),0<g&&o.node==f.previousSibling?(g=Math.min(a.count,g),a.previous.count+=g,i(a.previous,!0),a.count-=g,f.rowIndex+=g,u=0):c+=g);n.start=f.rowIndex-
u;f.rowIndex+=c}else{if(a.next)d(a.next,a.next.node.offsetTop-j,"previousSibling",!0),m=f.nextSibling,m==a.next.node?(a.next.count+=a.count-g,a.next.node.rowIndex=g+c,a.count=g,u=0):s=!0;n.start=a.count}n.count=c+u;if(s)s=m.offsetTop;i(a);f=l(m,"-div.dgrid-loading[style=height:"+c*b.rowHeight+"px]");l(f,"div.dgrid-"+(r?"below":"above"),b.loadingMessage);f.count=c;n.query=a.query;var x=a.query(n);if(void 0===b._trackError(function(){return x}))break;(function(a,c,d,e,f){p.when(b.renderArray(f,a,n),
function(){m=a.nextSibling;l(a,"!");e&&m&&(c.scrollTop+=m.offsetTop-e);d&&p.when(f.total||f.length,function(a){d.count=a-d.node.rowIndex;i(d)})})}).call(this,f,e,r,s,x);a=a.previous}}}})});