//>>built
define("dojo/cldr/nls/fi/gregorian",{"days-standAlone-short":"su,ma,ti,ke,to,pe,la".split(","),"months-format-narrow":"T,H,M,H,T,K,H,E,S,L,M,J".split(","),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"viikonp\u00e4iv\u00e4","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E d.M.yyyy","dateFormatItem-MMMEd":"ccc d. MMM",eraNarrow:["eK","jK"],"days-format-short":"su,ma,ti,ke,to,pe,la".split(","),"dateFormat-long":"d. MMMM y","months-format-wide":"tammikuuta,helmikuuta,maaliskuuta,huhtikuuta,toukokuuta,kes\u00e4kuuta,hein\u00e4kuuta,elokuuta,syyskuuta,lokakuuta,marraskuuta,joulukuuta".split(","),
"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"ip.","dateFormat-full":"cccc d. MMMM y","dateFormatItem-yyyyMEd":"E d.M.yyyy","dateFormatItem-Md":"d.M.","dayPeriods-standAlone-wide-pm":"ip.","dayPeriods-format-abbr-am":"ap.","dateFormatItem-yMd":"d.M.yyyy","dateFormatItem-yM":"L.yyyy","field-era":"aikakausi","months-standAlone-wide":"tammikuu,helmikuu,maaliskuu,huhtikuu,toukokuu,kes\u00e4kuu,hein\u00e4kuu,elokuu,syyskuu,lokakuu,marraskuu,joulukuu".split(","),"timeFormat-short":"H.mm",
"quarters-format-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"timeFormat-long":"H.mm.ss z","dateFormatItem-yMMM":"LLL y","dateFormatItem-yQ":"Q/yyyy","field-year":"vuosi","dateFormatItem-yyyyMMMM":"LLLL y","field-hour":"tunti","months-format-abbr":"tammikuuta,helmikuuta,maaliskuuta,huhtikuuta,toukokuuta,kes\u00e4kuuta,hein\u00e4kuuta,elokuuta,syyskuuta,lokakuuta,marraskuuta,joulukuuta".split(","),"dateFormatItem-yyQ":"Q/yy","timeFormat-full":"H.mm.ss zzzz",
"field-day-relative+0":"t\u00e4n\u00e4\u00e4n","field-day-relative+1":"huomenna","field-day-relative+2":"ylihuomenna","dateFormatItem-H":"H","months-standAlone-abbr":"tammi,helmi,maalis,huhti,touko,kes\u00e4,hein\u00e4,elo,syys,loka,marras,joulu".split(","),"quarters-format-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],"quarters-standAlone-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dateFormatItem-M":"L","days-standAlone-wide":"sunnuntai,maanantai,tiistai,keskiviikko,torstai,perjantai,lauantai".split(","),
"dateFormatItem-yyMMM":"LLLL yy","timeFormat-medium":"H.mm.ss","dateFormatItem-Hm":"H.mm","quarters-standAlone-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],eraAbbr:["eKr.","jKr."],"field-minute":"minuutti","field-dayperiod":"vuorokaudenaika","days-standAlone-abbr":"su,ma,ti,ke,to,pe,la".split(","),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"eilen","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"ap.",
"field-day-relative+-2":"toissap\u00e4iv\u00e4n\u00e4","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E d.M.","dateTimeFormat-full":"{1} {0}","dateFormatItem-yMMMMccccd":"cccc d. MMMM y","field-day":"p\u00e4iv\u00e4","days-format-wide":"sunnuntaina,maanantaina,tiistaina,keskiviikkona,torstaina,perjantaina,lauantaina".split(","),"field-zone":"aikavy\u00f6hyke","dateFormatItem-y":"y","months-standAlone-narrow":"T,H,M,H,T,K,H,E,S,L,M,J".split(","),"field-year-relative+-1":"viime vuonna","field-month-relative+-1":"viime kuussa",
"dateFormatItem-yyMM":"M.yy","dateFormatItem-hm":"h.mm a","dayPeriods-format-abbr-pm":"ip.","days-format-abbr":"su,ma,ti,ke,to,pe,la".split(","),"dateFormatItem-yMMMd":"d. MMM y",eraNames:["ennen Kristuksen syntym\u00e4\u00e4","j\u00e4lkeen Kristuksen syntym\u00e4n"],"days-format-narrow":"S,M,T,K,T,P,L".split(","),"days-standAlone-narrow":"S,M,T,K,T,P,L".split(","),"dateFormatItem-MMM":"LLL","field-month":"kuukausi","dayPeriods-format-wide-am":"ap.","dayPeriods-standAlone-wide-am":"ap.","dateFormat-short":"d.M.yyyy",
"field-second":"sekunti","dateFormatItem-yMMMEd":"E d. MMM y","field-month-relative+0":"t\u00e4ss\u00e4 kuussa","field-month-relative+1":"ensi kuussa","dateFormatItem-Ed":"E d.","field-week":"viikko","dateFormat-medium":"d.M.yyyy","field-year-relative+0":"t\u00e4n\u00e4 vuonna","field-week-relative+-1":"viime viikolla","dateFormatItem-yyyyM":"M.yyyy","field-year-relative+1":"ensi vuonna","dayPeriods-format-narrow-pm":"ip.","dateFormatItem-yyyyQQQQ":"QQQQ y","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H.mm.ss",
"dateFormatItem-hms":"h.mm.ss a","field-week-relative+0":"t\u00e4ll\u00e4 viikolla","field-week-relative+1":"ensi viikolla"});