//>>built
define("dojo/cldr/nls/pt/gregorian",{"days-standAlone-short":"dom,seg,ter,qua,qui,sex,s\u00e1b".split(","),"months-format-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","dateFormatItem-yQQQ":"y QQQ","dateFormatItem-yyMMMEd":"E, d 'de' MMM 'de' yy","dateFormatItem-yMEd":"E, dd/MM/yyyy","dateFormatItem-MMMEd":"E, d 'de' MMM",eraNarrow:["a.C.","d.C."],"dayPeriods-format-wide-morning":"manh\u00e3","days-format-short":"dom,seg,ter,qua,qui,sex,s\u00e1b".split(","),
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"janeiro,fevereiro,mar\u00e7o,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro".split(","),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dayPeriods-format-wide-noon":"meio-dia","dateFormatItem-yMd":"dd/MM/yyyy","field-era":"Era","dateFormatItem-yM":"MM/yyyy","months-standAlone-wide":"janeiro,fevereiro,mar\u00e7o,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro".split(","),
"timeFormat-short":"HH:mm","quarters-format-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z","field-year":"Ano","dateFormatItem-yMMM":"MMM 'de' y","dateFormatItem-yQ":"yyyy Q","field-hour":"Hora","dateFormatItem-MMdd":"dd/MM","months-format-abbr":"jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez".split(","),"dateFormatItem-yyQ":"Q yy","timeFormat-full":"HH:mm:ss zzzz","field-day-relative+0":"Hoje","field-day-relative+1":"Amanh\u00e3",
"field-day-relative+2":"Depois de amanh\u00e3","dateFormatItem-H":"HH","months-standAlone-abbr":"jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez".split(","),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"dateFormatItem-HHmmss":"HH:mm:ss","dateFormatItem-M":"L","days-standAlone-wide":"domingo,segunda-feira,ter\u00e7a-feira,quarta-feira,quinta-feira,sexta-feira,s\u00e1bado".split(","),"dateFormatItem-yyyyMMM":"MMM 'de' y",
"dateFormatItem-yyMMM":"MMM 'de' yy","timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["a.C.","d.C."],"field-minute":"Minuto","field-dayperiod":"Per\u00edodo do dia","days-standAlone-abbr":"dom,seg,ter,qua,qui,sex,s\u00e1b".split(","),"dayPeriods-format-wide-night":"noite","dateFormatItem-yyMMMd":"d 'de' MMM 'de' yy","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Ontem",
"dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","field-day-relative+-2":"Anteontem","dateFormatItem-MMMd":"d 'de' MMM","dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} {0}","field-day":"Dia","days-format-wide":"domingo,segunda-feira,ter\u00e7a-feira,quarta-feira,quinta-feira,sexta-feira,s\u00e1bado".split(","),"field-zone":"Fuso","dateFormatItem-yyyyMM":"MM/yyyy","dateFormatItem-y":"y","months-standAlone-narrow":"J,F,M,A,M,J,J,A,S,O,N,D".split(","),
"field-year-relative+-1":"Ano passado","field-month-relative+-1":"M\u00eas passado","dateFormatItem-yyMM":"MM/yy","dateFormatItem-hm":"h:mm a","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom,seg,ter,qua,qui,sex,s\u00e1b".split(","),"dateFormatItem-yMMMd":"d 'de' MMM 'de' y",eraNames:["Antes de Cristo","Ano do Senhor"],"days-format-narrow":"D,S,T,Q,Q,S,S".split(","),"days-standAlone-narrow":"D,S,T,Q,Q,S,S".split(","),"dateFormatItem-MMM":"LLL","field-month":"M\u00eas","dateFormatItem-HHmm":"HH:mm",
"dayPeriods-format-wide-am":"AM","dateFormat-short":"dd/MM/yy","dayPeriods-format-wide-afternoon":"tarde","field-second":"Segundo","dateFormatItem-yMMMEd":"E, d 'de' MMM 'de' y","field-month-relative+0":"Este m\u00eas","field-month-relative+1":"Pr\u00f3ximo m\u00eas","dateFormatItem-Ed":"E, d","field-week":"Semana","dateFormat-medium":"dd/MM/yyyy","field-year-relative+0":"Este ano","field-week-relative+-1":"Semana passada","field-year-relative+1":"Pr\u00f3ximo ano","dayPeriods-format-narrow-pm":"p",
"dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","field-week-relative+0":"Esta semana","field-week-relative+1":"Pr\u00f3xima semana"});